management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
eureka:
  client:
      serviceUrl:
        defaultZone: http://localhost:10010/eureka/